apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: moni
spec:
  ports:
    - port: 3000
      NodePort: 30815
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP