apiVersion: v1
kind: Service
metadata:
  name: orcl-exporter-svc
  namespace: moni
  labels:
    app: oracle-exporter
    release: stable
spec:
  type: ClusterIP
  ports:
    - port: 9161
      name: metrics
      targetPort: 9161
  selector:
    app: oracle-exporter