apiVersion: v1
kind: Service
metadata:
  name: prome-svc
  namespace: moni
  labels:
    app: prometheus
    release: stable
spec:
  type: ClusterIP
  ports:
    - port: 9090
      name: metrics
      targetPort: 9090
  selector:
    app: prometheus