apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: moni
  labels:
    app: node-exporter
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
    - name: node-metrics
      port: 9100
      targetPort: metrics