apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AhmedSoliman92/k8s-monitoring.git
    path: apps/dev/grafana/overlays
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: moni
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
